name: Pull Request Build
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, closed]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - name: Build docs
        run: |
          cd ChunkyDocs
          mkdocs build
      - name: Deploy preview
        uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: ./ChunkyDocs/site/
          teardown: 'true'
          build: |
            echo ""
